### ISSUE TITLE
Tasks to make Svelte official ESLint plugin

### ISSUE THREAD

**Issue by ota-meshi** [sveltejs/eslint-plugin-svelte#431]
I would like to list tasks to make this package the default eslint-plugin. 

Note: however, that this list has not yet taken consensus.

- ~~Renaming package names.~~
  ~~- [ ] `eslint-plugin-svelte` -> `@sveltejs/eslint-plugin` ?~~ -> No change.
  ~~- [ ] `svelte-eslint-parser` -> `@sveltejs/eslint-parser` ?~~ -> No change.
  ~~- [ ] Add migration documentation for package name change~~
- [x] Change the [`Why?` section](https://github.com/sveltejs/eslint-plugin-svelte/blob/main/README.md#-why) of the README.
  - https://github.com/sveltejs/eslint-plugin-svelte3/pull/204
  - #441
  - https://github.com/sveltejs/svelte-eslint-parser/pull/321
- [x] Change the eslint-plugin that `svelte`/`sveltekit` installs by default from eslint-plugin-svelte3 to eslint-plugin-svelte.
  - https://github.com/sveltejs/kit/pull/9749
- [x] Change the Svelte plugin listed in [Awesome ESLint](https://github.com/dustinspecker/awesome-eslint).
  - https://github.com/dustinspecker/awesome-eslint/pull/210

---

~~I have a question.~~
~~Should we change the package name? (I'm not against renaming)~~
~~I think the new package name gives a good indication that it's official.~~
~~However, the names of rules and the configs provided by this plugin, may be a bit lengthy and redundant.~~
~~e.g. `svelte/rule-name` -> `@sveltejs/rule-name`~~
~~Also, current eslint-plugin-svelte users will need to migrate.~~

---

Related issues:

https://github.com/sveltejs/kit/issues/6847
https://github.com/sveltejs/kit/issues/9342

**Comment by DetachHead** [comment]
great to see that this plugin is now part of @sveltejs! 

looks like the link in the about section on github needs to be updated to https://sveltejs.github.io/eslint-plugin-svelte/
![image](https://user-images.githubusercontent.com/57028336/229420043-223af384-f8b0-438c-8b65-68ef894e6e43.png)
![image](https://user-images.githubusercontent.com/57028336/229420078-6655497e-198b-42d5-ac7f-580c064d35a7.png)

**Comment by ota-meshi** [comment]
Yeah, I'm no longer able to edit it as the repositories have been transferred.
I'm letting @baseballyama know that for now, as I still don't know which chat and who to contact to get this resolved 😅.

> great to see that this plugin is now part of @sveltejs

Thanks!

**Comment by baseballyama** [comment]
I requested @Rich-Harris about the authority yesterday on Discord, so I hope we can update this today.

**Comment by baseballyama** [comment]
I discussed with maintainers and we decided that we don't change package names.👍 @ota-meshi

**Comment by ota-meshi** [comment]
Thanks to @baseballyama, we completed all the necessary tasks. Thank you!
