### ISSUE TITLE
Add support for Svelte v4.

### ISSUE THREAD

**Issue by ota-meshi** [sveltejs/eslint-plugin-svelte#449]
We haven't caught any issues with Svelte v4 yet. Please comment if you think there is a problem in combination with the eslint-plugin.

Related to https://github.com/sveltejs/svelte/pull/8480

**Comment by benmccann** [comment]
`peedDependencies` will need to include `|| ^4.0.0` or `|| ^4.0.0-next.0`

**Comment by ota-meshi** [comment]
Thank you for letting me know. I will try that later.

**Comment by kolberg-dev** [comment]
The[ valid-compile](https://sveltejs.github.io/eslint-plugin-svelte/rules/valid-compile/) rule do not seem to support the new  [customElement] option (https://github.com/sveltejs/svelte/blob/258db329bc6cebd20d652031c2fe9efd0b67630c/documentation/docs/05-misc/04-v4-migration-guide.md#custom-elements-with-svelte)

![Screenshot 2023-06-22 at 10 22 09](https://github.com/sveltejs/eslint-plugin-svelte/assets/74478295/85c04347-5192-47b0-892b-82a8cbf05386)
