### ISSUE TITLE
Use `pnpm` or update `package.json`

### ISSUE THREAD

**Issue by baseballyama** [sveltejs/eslint-plugin-svelte#474]
dominikg is started to implement [svelte-ecosystem-ci](https://github.com/sveltejs/svelte-ecosystem-ci) and it includes this ESLint plugin also.

For this CI to be successful, either of the following must be implemented
- Use `pnpm`
- Add `"packageManager":"yarn@version"` to `package.json`

I personally want to use pnpm because now both Svelte and SvelteKit is using pnpm.
Then we can think that we can always use pnpm for Svelte repositories.
And I think pnpm is much faster...

**Comment by ota-meshi** [comment]
I think it's a good idea to use organization's familiar package manager! Let's change ours to use `pnpm` too.

**Comment by baseballyama** [comment]
close this because https://github.com/sveltejs/eslint-plugin-svelte/pull/477 is merged.
