### ISSUE TITLE
The ESLint rule checking is not working.

### ISSUE THREAD

**Issue by XLearner** [sveltejs/eslint-plugin-svelte#485]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.39.0

### What version of `eslint-plugin-svelte` are you using?

2.27.3

### What did you do?

<details>
<summary>Configuration</summary>

```
# .eslintrc.yml
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:svelte/base
  - plugin:@typescript-eslint/recommended
  - prettier
overrides:
  [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      parserOptions: { parser: '@typescript-eslint-parser' },
    },
    { files: ['*.js'], parser: 'none' },
  ]
parser: '@typescript-eslint/parser'
parserOptions:
  project: '**/tsconfig.json'
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - '.svelte'
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
  - 'svelte'
rules:
  {
    'simple-import-sort/exports': 2,
    'simple-import-sort/imports': 2,
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/no-unused-vars': 2,
    'no-console': 'error',
  }

```
</details>

```svelte
<script lang="ts">
console.log('test'); // error!  there is no emitting error tip.
</script>

<div>test</div>
```

### What did you expect to happen?

The statement of `console.log` should emit an error tip like the following image.

![image](https://github.com/sveltejs/eslint-plugin-svelte/assets/26158725/c5b4f6ed-9ea5-4128-b0ad-98d699a2cda9)

### What actually happened?

no error tips.

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/XLearner/svelte-eslint-demo

**Comment by ota-meshi** [comment]
It looks like the ESLint configuration is incorrect in the repository you shared.
Just including `svelte` in the plugins array in your ESLint configuration will not work. Please refer to the README and documentation to configure ESLint to work well.

**Comment by XLearner** [comment]
> It looks like the ESLint configuration is incorrect in the repository you shared. Just including `svelte` in the plugins array in your ESLint configuration will not work. Please refer to the README and documentation to configure ESLint to work well.

I try to config `.eslintrc.yml` like the following code with the guidance of `README.md` and supplement the missing plugins. 

This is the description in the `README.md`:
![image](https://github.com/sveltejs/eslint-plugin-svelte/assets/26158725/987fa869-7617-411d-9444-ac4727bd0615)

```
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:svelte/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: latest
  sourceType: module
  extraFileExtensions:
    - '.svelte'
overrides: [
  {
    files: ["*.svelte"],
    parser: "svelte-eslint-parser",
    parserOptions: {
      parser: "@typescript-eslint/parser"
    }
  }
]
plugins:
  - '@typescript-eslint'
  - 'simple-import-sort'
  - 'svelte'
rules:
  {
    'simple-import-sort/exports': 2,
    'simple-import-sort/imports': 2,
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/no-unused-vars': 2,
    'no-console': 'error',
  }

```

If I run this command `eslint src --ext .svelte`, my terminal will emit `Unexpected console statement no-console`. 
![image](https://github.com/sveltejs/eslint-plugin-svelte/assets/26158725/dd282d9c-0a41-46ab-968e-dc62cb77785d)

![image](https://github.com/sveltejs/eslint-plugin-svelte/assets/26158725/8b2069de-a77a-4766-a49c-3211f9a0d93a)

However, the editing page of the VSCode has still not the red underline. Is it expected? 

Actually, I want to get the feedback directly from the editing page about the `no-console` error instead of invoking the command of `eslint src --ext .svelte`.

**Comment by ota-meshi** [comment]
See the documentation for configuring VSCode.

https://sveltejs.github.io/eslint-plugin-svelte/user-guide/#visual-studio-code
