### ISSUE TITLE
Rule Proposal: `svelte/component-tags-order`

### ISSUE THREAD

**Issue by Shyam-Chen** [sveltejs/eslint-plugin-svelte#493]
### Description

Refs:
- https://eslint.vuejs.org/rules/component-tags-order.html
- https://eslint.vuejs.org/rules/define-macros-order.html

```svelte
<!-- ✓ GOOD -->
<svelte:options />

<script context="module">/* ... */</script>
<script>/* ... */</script>

<svelte:head>/* ... */</svelte:head>

<svelte:window />
<svelte:document />
<svelte:body />

<div>...</div>
<div>...</div>

<style>/* ... */</style>
```

```svelte
<!-- ✓ GOOD -->
<script>
  import { page } from '$app/stores';
</script>

<svelte:head>
  <title>{$page.data.title}</title>
</svelte:head>

<div>...</div>
```

**Comment by marekdedic** [comment]
Hi, let me argue against adding this rule:

This is already covered by `prettier-plugin-svelte` as described in its [docs](https://github.com/sveltejs/prettier-plugin-svelte#svelte-sort-order). Please don't duplicate this.
