### ISSUE TITLE
"plugin:svelte/recommended" not working

### ISSUE THREAD

**Issue by t-lock** [sveltejs/eslint-plugin-svelte#503]
`extends: ["plugin:svelte/recommended"]` results in nothing being linted.

However:

- any rule explicitly added to `rules` works as expected
- `plugin:svelte/all` works as expected
- `eslint:recommended` works as expected
- rules defined in .svelte files with pragma work as expected, e.g: `/* eslint svelte/infinite-reactive-loop: "error" */`  inside  a `<script>` tag in a `.svelte` file

Using Svelte/Typescript and the following config, pasted from the documentation:

```
module.exports = {
  // ...
  extends: ["plugin:svelte/recommended"],
  // ...
  parser: "@typescript-eslint/parser",
  parserOptions: {
    // ...
    project: "tsconfig.json",
    extraFileExtensions: [".svelte"], // This is a required setting in `@typescript-eslint/parser` v4.24.0.
  },
  overrides: [
    {
      files: ["*.svelte"],
      parser: "svelte-eslint-parser",
      // Parse the `<script>` in `.svelte` as TypeScript by adding the following configuration.
      parserOptions: {
        parser: "@typescript-eslint/parser",
      },
    },
    // ...
  ],
  // ...
};

```

Any advice or ideas on troubleshooting would be much appreciated!!

**Comment by baseballyama** [comment]
Quickly I tried to run a new kit repository with your config, but I can get lint errors.
Can you provide us a repl repository?
