### ISSUE TITLE
Generic declarations in components not recognized by ESLint

### ISSUE THREAD

**Issue by MathiasFrost** [sveltejs/eslint-plugin-svelte#521]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.43.0

### What version of `eslint-plugin-svelte` are you using?

2.10.1

### What did you do?

<details>
<summary>Configuration</summary>

```
module.exports = {
	root: true,
	extends: ["eslint:recommended", "plugin:@typescript-eslint/recommended", "plugin:svelte/recommended", "prettier"],
	parser: "@typescript-eslint/parser",
	plugins: ["@typescript-eslint"],
	parserOptions: {
		sourceType: "module",
		ecmaVersion: 2020,
		extraFileExtensions: [".svelte"]
	},
	env: {
		browser: true,
		es2017: true,
		node: true
	},
	overrides: [
		{
			files: ["*.svelte"],
			parser: "svelte-eslint-parser",
			parserOptions: {
				parser: "@typescript-eslint/parser"
			}
		}
	]
};

```
</details>

```svelte
<script lang="ts" generics="T">
	import { createEventDispatcher } from "svelte";

	// Or type T = $$Generic; (same result)

	/** */
	const dispatch = createEventDispatcher<{ change: Promise<T> }>();

	export let value: T;

	/** */
	function test(): void {
		const promise = new Promise<T>((resolve) => resolve(value));
		dispatch("change", promise);
	}
</script>
```

### What did you expect to happen?

That ESLint would be able to interpret the symbol `T`

### What actually happened?

ESLint is not able to interpret the symbol `T`:
```log
   6:59  error    'T' is not defined                     no-undef
   8:20  error    'T' is not defined                     no-undef
```

### Link to **GitHub Repo** with Minimal Reproducible Example

[playground](https://sveltejs.github.io/eslint-plugin-svelte/playground/#eJyNVsty6zYM/RWNVk4mnMx0mSZZtfsusvSGoiCbNUXqkpRj30z+vQfU+5GZrmwCEIjHwQG/cuVKyl/y16C8buLRZtmJLHmtwtsx/zjmLDHSnnCKoTuGCHX8+0o2hncW6LpxPmZfmfIkIyXNXzo0Mqoz+ew7q7yrs2MermQiHfM/j5Y/e358zB6f+Z9yNsSs7D/J3vYdveKCM0Khl+wfONSBXj/es+/3w0PvkG4pDkMxu0rTwu5jc1XVWhW1s1mkEA8PL9nV6TL7YtUQR9M5RxiWPmdXHQ6egjNXesje3rP+/yHd9MAhsIchh8Mx72I95k+Dw87m+2hfn7tqo3j5U+5bQyF/+erL81y0MTorzjKIeG/QnD+eBpVydY2SiFJ7QhbXhbJE165Upg+DrElo27QxCNdG/p2bolAwZlfSCE+/WvgTwbiYbvwfpgkBghIE5taV9iEKGaFHGiSMtlSgl5e50TnWRijjgrYnUXipLhQFyqZw3tj9al1cRpTEgUw1+JgrtS0R01JSaasRC8JINRPGuWZuUcvbFHIQyDfFvTBpQ5TA4F6Y1uFrUVLRnkSUp7DVpYh3VKWrRS2tbloj49Zr2TYkyAR0shKFceqyccAWwMqIh12DEO+GBECIzKLet2lxy89e7lbWWnUIwV9a6ekWvZzqq1pvttfoum6jLMysEahppHqNIba1oCCUVBnpJU/r2sAikGGSAXhbGvIrE1f8i2zgSkTEJ4YOrj2NwQzufjQwAJGX5kc9/oSgT3aj76aFJ5NxQGY35XAGdXEmy3bdhbuS97rcBM5IBFqldy0+wmBiPvn6wCmPcF5/FB3GV4a7VStNlP6EMSzA9Ze1yktteFa7K1fa1l6s+7R92COGxgQ25oBaidFFsfaw1Os7gUA+CHhtguEnfL3b0sZTBex0/nd5srcouS+tiq3n61JdOOQ9Z6vU5hYDIwIEZ3Gh+67u2nH2sMe2JDtYuibqWv+mAQS7bZxImGNW0pgCFBrSCAe0sMHM1D9/MOJVKjRzN4xkyDjSCyadILob16TerVSAdkazCxXjqh+PfsUt1PcAmphLsHN1yaaNNrRVLJqRdjo32qGRoLqOJyqc+jBdN7FAP+Yb5QEiOgmTN0+K6Pc3eI5UCz+DVklmzTVLsSKhb0YHLEO0EsW1dBK/ybtJzgVdmVreoluZBI7YXo9Rd5roHS/nE90GYVpHJ/LTGa8iElc5SZj2MfRhIegir6kuyC81/SJayFDjuZHRCoSeyjJIqW56ChgOAu8i7Pw4DOlSiRGBZsyNbqsydKumcM6QtHxTXGoC1XqQVBiNeAY/ns6jCCS/8ngyrgB1LoXdi3YttB28UqGbUepxxgL34vOMDZGwPOjwPsH7qwKASOkw6xnghARKJtUfylHrG9NAT/KACHbnqMS7VIR7XTgzSpx1ip9ogKOu8UtByWYMBMswMcXoIRkPB+A7OiYlUbTa4CUymoEbE7xpEiD3+SLgpcJvsWWpwt4whbMs3ed8ITL/T24wHoEh6eWEqnjWQRRUMXNN05v2REnVdOBnanJZt0hgfL4lHTPemV8ekyjIChtfW5TkvpJiPuV8vHoxU7ODPfcLxNg/1qaFZWRBU3l7IcZtEvVbi8k6rRWyE1AGpeINsRYuW/mpY2cxsPVdkymThDeADlZ2sXdg5bY6LtT393/IJOb9)

### Additional comments

Note that this is not an issue in eslint-plugin-svelte3.  

Also don't know if `generic="T"` attribute or `type T = $$Generic` declaration is the preferred way of dealing with generics in components, but both seem to not work.

**Comment by christophsturm** [comment]
`generics="T"` is the new syntax and type `T = $$Generic` is the old one. both seem to not work. the old syntax works with `eslint-plugin-svelte3`. my workaround is to go back to `eslint-plugin-svelte3` and the old syntax for now.

**Comment by ota-meshi** [comment]
As for adding support for `Generic`, it's strictly a parser issue.
Follow https://github.com/sveltejs/svelte-eslint-parser/issues/306.

**Comment by MathiasFrost** [comment]
> As for adding support for `Generic`, it's strictly a parser issue. Follow [sveltejs/svelte-eslint-parser#306](https://github.com/sveltejs/svelte-eslint-parser/issues/306).

I'm not sure I understand. Is this a `svelte-eslint-parser` issue then? And if so, why is `eslint-plugin-svelte3` the only enabling the use of `$$Generic`?

**Comment by ota-meshi** [comment]
eslint-plugin-svelte3 and eslint-plugin-svelte are completely separate packages. eslint-plugin-svelte3 does not use svelte-eslint-parser. If you want immediate support, please submit a pull request.

**Comment by BeeMargarida** [comment]
I hit this problem as well. Is there a workaround for now?

**Comment by MathiasFrost** [comment]
> I hit this problem as well. Is there a workaround for now? If someone points me in the right direction, I would like to help with a fix.

The workaround is just not using it and going back to `eslint-plugin-svelte3`, like @christophsturm said.

**Comment by MathiasFrost** [comment]
> I hit this problem as well. Is there a workaround for now? If someone points me in the right direction, I would like to help with a fix.

I took a brief look and think it looks like `eslint-plugin-svelte3` is just ignoring the `no-undef` error and letting the svelte language tools handle it (?), in which case `svelte-eslint-parser` just has to do the same?

I am also not sure how "set in stone" this generics-declaration-by-attributes is, considering it is [a PR on svelte repo atm](https://github.com/sveltejs/rfcs/pull/38), as well as [this warning on svelte.dev](https://svelte.dev/docs/typescript#experimental-advanced-typings)

**Comment by ota-meshi** [comment]
If you just want to avoid the `$$Generic` variable being flagged for `no-undef` rule, just set it to `globals` in the ESLint configuration.

https://eslint.org/docs/latest/use/configure/language-options#using-configuration-files-1

**Comment by ota-meshi** [comment]
Follow sveltejs/svelte-eslint-parser#306 on this subject. I will lock this thread.
