### ISSUE TITLE
bug: plugin:@typescript-eslint/recommended rules aren't applied to TypeScript inside *.svelte files

### ISSUE THREAD

**Issue by uh-zuh** [sveltejs/eslint-plugin-svelte#632]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.53.0

### What version of `eslint-plugin-svelte` are you using?

2.35.0

### What did you do?

<details>
<summary>Configuration</summary>

Significant part of `npm ls`:
```
+-- @tsconfig/svelte@5.0.2
+-- @typescript-eslint/eslint-plugin@6.10.0
+-- @typescript-eslint/parser@6.10.0
+-- eslint-plugin-svelte@2.35.0
+-- eslint@8.53.0
+-- svelte@4.2.2
+-- tslib@2.6.2
+-- typescript@5.2.2
```

config\.eslintrc.cjs:
```
module.exports = {
    extends: [
        'eslint:recommended',
        'plugin:@typescript-eslint/recommended',
        'plugin:svelte/recommended',
    ],
    plugins: [
        '@typescript-eslint',
    ],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        project: [
            'config/tsconfig.main.json',
        ],
        extraFileExtensions: ['.svelte'],
    },
    overrides: [
        {
            files: [
                '*.svelte',
            ],
            parser: 'svelte-eslint-parser',
            // Parse the `<script>` in `.svelte` as TypeScript by adding the following configuration.
            parserOptions: {
                parser: '@typescript-eslint/parser',
            },
        },
    ],
    rules: {
        //'prefer-const': 'error',
    },
};
```

config\tsconfig.main.json:
```
{
    "extends": "@tsconfig/svelte/tsconfig.json",
    "compilerOptions": {
        "target": "ESNext",
        "useDefineForClassFields": true,
        "module": "ESNext",
        "resolveJsonModule": true,
        "allowJs": true,
        "checkJs": true,
        "isolatedModules": true,
    },
    "include": [
        "../src/**/*.d.ts",
        "../src/**/*.ts",
        "../src/**/*.js",
        "../src/**/*.svelte",
    ],
}
```
</details>

test.ts:
```typescript
let a1 = 1;
var b1 = 2;
const key1 = "a";
const obj1 = {};
if (!key1 in obj1) {
}
```

Test.svelte:
```svelte
<script lang="ts">
let a2 = 1;
var b2 = 2;
const key2 = "a";
const obj2 = {};
if (!key2 in obj2) {
}
</script>
```

I run eslint on these files.

### What did you expect to happen?

See following errors.

For `test.ts`:
```
error  'a1' is never reassigned. Use 'const' instead  prefer-const
error  Unexpected var, use let or const instead       no-var
```

For 'Test.svelte':
```
error  'a2' is never reassigned. Use 'const' instead  prefer-const
error  Unexpected var, use let or const instead       no-var
```

I expect to see same errors for TypeScript code in both files.

### What actually happened?

See following errors.

For `test.ts`:
```
error  'a1' is never reassigned. Use 'const' instead  prefer-const
error  Unexpected var, use let or const instead       no-var
```

For 'Test.svelte':
```
error  Unexpected negating the left operand of 'in' operator  no-unsafe-negation
```

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/uh-zuh/eslint-plugin-svelte_bug_reproduction_typescript

#### Reproducton
In reproduction repository:
Run `npm run lint:with_bug` to see bug.
Run `npm run lint:with_hotfix` to see desired behavior.

#### Description of the bug

In ESLint config:
```
extends: [
    ...,
    'plugin:@typescript-eslint/recommended',
]
```
`plugin:@typescript-eslint/recommended` is this:
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/recommended.ts
and it includes this:
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts
which turns on and off some rules, for example this:
```
        'no-unsafe-negation': 'off',
        'no-var': 'error',
        'prefer-const': 'error',
```
It works well for TypeScript in *.ts files but it doesn't work for TypeScript in *.svelte files.

As workaround I found a way to copy content of `eslint-recommended.ts` to my config but is ugly.

In the reproduction repository I have copied this 3 rules to my ESLint config to demonstrate that eslint-plugin-svelte ignores TypeScript rules which are used for all other TypeScript code in *.ts files.

**Comment by ota-meshi** [comment]
`eslint-recommended.ts` is defined as `files: ['*.ts', '*.tsx', '*.mts', '*.cts']`, so the `*.svelte` file is not included.

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/configs/eslint-recommended.ts

I think you need to import typescript-eslint and define the rules yourself.

```js
const config = require('@typescrit-eslint/eslint-plugin').config["eslint-recommended"]

module.exports = {
     /* ... */
     overrides: [
         {
             files: ['*.svelte'],
             rules: config.overrides[0].rules
         }
     ]
}
```

**Comment by uh-zuh** [comment]
Thanks.
Could you add this to README in scetion about TypeScript?

**Comment by uh-zuh** [comment]
@ota-meshi, should I create new issue for updating README?

**Comment by baseballyama** [comment]
I think this is not Svelte's ESLint plugin issue but general ESLint question.
But PRs are welcome!
Maybe we can mention about this as tips.
