### ISSUE TITLE
2.36 release

### ISSUE THREAD

**Issue by benmccann** [sveltejs/eslint-plugin-svelte#667]
### Description

I was wondering if it might be possible to get a release for 2.36.0? Then we could update the SvelteKit templates to address https://github.com/sveltejs/kit/issues/11530

**Comment by JounQin** [comment]
I'd like to release a major version to drop Node <18 which aligns with Svlete itself.

See also #665.

**Comment by ota-meshi** [comment]
I don't think AST in svelte v5 is stable yet, so svelte-eslint-parser is also not stable. Therefore, I don't think it is possible to release the stable version of eslint-plugin-svelte v2.36 yet.

**Comment by JounQin** [comment]
@ota-meshi We can use https://github.com/un-ts/preversion to release alpha versions very easily, shall I raise a PR for it?

**Comment by ota-meshi** [comment]
I'm currently using changeset pre mode. It's working fine so far.

https://github.com/sveltejs/eslint-plugin-svelte/pull/658#:~:text=is%20currently%20in-,pre%20mode,-so%20this%20branch

**Comment by JounQin** [comment]
Nice

**Comment by benmccann** [comment]
I probably could use the next tag. I just assumed you'd be releasing 2.36 soon because otherwise it's a long time to go without another release. I don't think there's any expectation for anything related to Svelte 5 to be stable regardless of version number. And it would be easier to give the same version to all users. But I can make it work either way, so gee
