### ISSUE TITLE
bun install fails for complex dependency version

### ISSUE THREAD

**Issue by RobinKnipe** [sveltejs/eslint-plugin-svelte#715]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.57.0

### What version of `eslint-plugin-svelte` are you using?

2.36.0-next.12

### What did you do?

```shell
bun create svelte@latest
# choose eslint, prettier, svelte5
bun install
```

### What did you expect to happen?

Dependencies install successfully

### What actually happened?

`bun` fails to process the composite version syntax `">=0.34.0-next.12 <1.0.0"` and errors without adding any modules!
```shell
$ bun install
bun install v1.0.26 (c75e768a)
warn: incorrect peer dependency "svelte@5.0.0-next.80"

error: No version matching ">=0.34.0-next.12 <1.0.0" found for specifier "svelte-eslint-parser" (but package exists)
```

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/RobinKnipe/eslint-plugin-svelte-issue

### Additional comments

PR for suggested fix: https://github.com/sveltejs/eslint-plugin-svelte/pull/714

**Comment by ota-meshi** [comment]
I think it's a bug in `bun`. I think that version specification needs to be valid.

**Comment by RobinKnipe** [comment]
> I think it's a bug in `bun`. I think that version specification needs to be valid.

It is a shortcoming of the bun version support, sure. But given the problem can be fixed by merely simplifying the version number, why not do that? The 2 versions are semantically the same, so as a general rule try to use the more brutally supported style, no?

**Comment by ota-meshi** [comment]
They are not actually the same. I use that syntax intentionally.

**Comment by RobinKnipe** [comment]
Ok, I'll continue to use the fork until the situation improves. Thanks
