### ISSUE TITLE
Bindable props are treated as unused variables by eslint in some cases.

### ISSUE THREAD

**Issue by ptrxyz** [sveltejs/eslint-plugin-svelte#768]
Since this came up today and Thomas G. Lopes mentioned the possibility of having the issue handled by Svelte's eslint plugin I want to cross post the issue https://github.com/sveltejs/svelte/issues/11901 here:

When creating a component like this:

![image](https://github.com/sveltejs/eslint-plugin-svelte/assets/209056/1d5d77d2-7b1e-4aa3-b3c9-9601be944d2a)

The prop is treated as unread variable yet it should rather be treated as an exported variable since it might still be read from outside.

**Comment by ota-meshi** [comment]
Thank you for posting the issue!
I think we need to fix the parser. But I don't have time to do that right now.
