### ISSUE TITLE
Linting issue "Parsing error: value.find is not a function"

### ISSUE THREAD

**Issue by kunalshah** [sveltejs/eslint-plugin-svelte#826]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.7.0

### What version of `eslint-plugin-svelte` are you using?

2.42.0

### What did you do?

<details>
<summary>After upgrading to latest version of svelte (5.0.0-next.190), eslint shows linting error "Parsing error: value.find is not a function". There was no error with svelte version "5.0.0-next.184". One of the change with svelte 5.0.0-next.190 is that the values passed to components are not to be enclosed in string, and that probably is causing the issue with the eslint-plugin-svelte
</summary>

```
[https://github.com/kunalshah/my-app/blob/main/eslint.config.js](https://github.com/kunalshah/my-app/blob/main/eslint.config.js)
```
</details>

```svelte
Repo: https://github.com/kunalshah/my-app

"npm run lint" to see the issue being reproduced.
```

### What did you expect to happen?

There should not have been any linting errors.

### What actually happened?

Linting error:
  0:0  error  Parsing error: value.find is not a function

### Link to **GitHub Repo** with Minimal Reproducible Example

[https://github.com/kunalshah/my-app](https://github.com/kunalshah/my-app)

or

[https://stackblitz.com/~/github.com/kunalshah/my-app](https://stackblitz.com/~/github.com/kunalshah/my-app)

**Comment by cabreraalex** [comment]
I'm still getting this issue with newest version - any trick to fixing it?
