### ISSUE TITLE
Tag braces style

### ISSUE THREAD

**Issue by coldfeudal** [sveltejs/eslint-plugin-svelte#833]
Is there any way to enforce tag `< />` linebreak style?

E.g. transform this
```html
<div
  class="device-image bc"
  style:background-image="url('/devices/{backgroundImage}')" />
```
into this
```html
<div
  class="device-image bc"
  style:background-image="url('/devices/{backgroundImage}')"
/>
```
Ideally only for tags with multiple lines/arguments

**Comment by mikededo** [comment]
The feature is tracked in here: https://github.com/sveltejs/eslint-plugin-svelte/issues/590

**Comment by baseballyama** [comment]
`svelte/html-closing-bracket-new-line` can solve this issue.
