### ISSUE TITLE
Suppress prefer-const warnings for $props() and $derived()

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/eslint-plugin-svelte#889]
I'm not sure what mechanism is being used to suppress prefer-const warnings for variables that have `bind:`s in the template, but these warnings should also be suppressed for `$props()` and `$derived()`. Using a `const` for a `$derived()` feels like a weird thing to force on people, and a mixture of bindable and non-bindable `$props()` can cause more serious issues where ESLint will encourage components that can't be compiled - https://github.com/sveltejs/svelte/issues/13897

**Comment by ryanatkn** [comment]
A workaround for props is using the [`destructuring: all`](https://eslint.org/docs/latest/rules/prefer-const#destructuring) option in `prefer-const` for Svelte files.

**Comment by ilyakamens** [comment]
I'm also encountering this with `$derived()` and `$derived.by()`.

**Comment by baseballyama** [comment]
Fixed by https://github.com/sveltejs/eslint-plugin-svelte/pull/933

**Comment by ilyakamens** [comment]
Thank you!
