### ISSUE TITLE
`no-inline-styles`: Change the default value for `allowTransitions` to true

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/eslint-plugin-svelte#902]
The `no-inline-styles` rule has an option controlling whether it reports the use of transitions as well. This was largely due to the fact that the built-in Svelte 4 transitions used inline styles and thus using them wasn't "safe" in a no-inline-styles webpage.

With Svelte 5, transitions [apparently](https://github.com/sveltejs/svelte/issues/6662#issuecomment-2452551888) no longer use inline styles. Thus, I'd like to change the default behaviour of the rule to allowing transitions (I think we can keep the option to disallow them for those who want it.)

**Comment by ota-meshi** [comment]
Wow, I didn't know that! The rule changes sound good to me!
