### ISSUE TITLE
Future of `no-not-function-handler`

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/eslint-plugin-svelte#903]
Hi, the rule `no-not-function-handler` is used in Svelte 4 for checking that event callbacks are functions. In Svelte 5, event callbacks are regular props. I think the rule shouldn't be ported to this new event system for several reasons:

1. You can't really tell which prop is an event callback
2. Passing non-functions to props which expect a callback is like passing any wrongly typed prop, sou should be caught if you are using TypeScript (and if you are not... well that's your choice, this is exactly the kind of issue that TypeScript was built for...)

What do you think?

**Comment by ota-meshi** [comment]
Yeah. I agree with you, I don't think that rule is very useful.

**Comment by marekdedic** [comment]
Ok, I'll add it to the list.
