### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/eslint-plugin-svelte#907]
Hi,
seeing the conversation in https://github.com/sveltejs/eslint-plugin-svelte/pull/899#discussion_r1827225654, I'd like to clarify the roadmap for this plugin if possible - so that us contributors know what to count on in the future. The way I read the discussion, it seems to me to be like this:

| `eslint-plugin-svelte` version | Svelte 4 support | Svelte 5 support |
| --- | --- | --- |
| 2 | Full support | No support |
| 3 | Full support, removal of Svelte-4-specific rules from `recommended` | Full support |
| 4 | Deprecated | Full support |
| 5 | ??? | Full support |

Is this correct?

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
I don’t have a plan for whether or not to drop support for Svelte v4.
But I think it will probably look something like the table you wrote.

**Comment by baseballyama** [comment]
Thank you for posting the issue!
I created a issue about this.
https://github.com/sveltejs/eslint-plugin-svelte/issues/966

(In particular, we would like to finalize the scope of support for eslint-plugin-svelte v4 depending on how many users stay with Svelte4.)
