### ISSUE TITLE
Clarification of Versioning Policy

### ISSUE THREAD

**Issue by ota-meshi** [sveltejs/eslint-plugin-svelte#948]
I've followed ESLint's versioning policy as much as possible, but I think it's blocking useful new features from reaching our users.

https://github.com/eslint/eslint/blob/main/README.md#semantic-versioning-policy

I think it would be better for us to allow changes to the default behavior of rules and shareable configuration in minor versions.
And make that clear in the documentation.
What do you think?

Please also refer to https://github.com/vuejs/eslint-plugin-vue/pull/2630

**Comment by baseballyama** [comment]
Agreed 💯
