### ISSUE TITLE
docs: `eslintPluginSvelte.configs.recommended` is not iterable

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/eslint-plugin-svelte#967]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.17.0

### What version of `eslint-plugin-svelte` are you using?

2.46.1

### What did you do?

i followed [the docs](https://github.com/sveltejs/eslint-plugin-svelte?tab=readme-ov-file#configuration)

![image](https://github.com/user-attachments/assets/96d829b7-0982-436d-a53c-fd646adf2a26)

### What did you expect to happen?

work

### What actually happened?

didn't work. instead:

`TypeError: eslintPluginSvelte.configs.recommended is not iterable`

### Link to **GitHub Repo** with Minimal Reproducible Example

n/a

**Comment by baseballyama** [comment]
README on main branch is for eslint-plugin-svelte v3.
For 2.46.1, please see https://github.com/sveltejs/eslint-plugin-svelte/blob/eslint-plugin-svelte%402.46.0/README.md
